name: Build Octoprint with improvements

on:
  push:
  schedule:
    - cron: '0 3 * * WED'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v1
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build ${{ matrix.variant }}
        uses: docker/build-push-action@v2
        with:
          target: result
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: matthewbaggett/octoprint


